name: Run SQL Tests

on: [push, pull_request]

jobs:
  test-sql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sakila
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Wait for MySQL to be ready
      run: |
        for i in {30..0}; do
          mysqladmin ping -h 127.0.0.1 -uroot -proot && break
          echo 'Waiting for MySQL...'
          sleep 1
        done

    - name: Load schema
      run: mysql -h 127.0.0.1 -uroot -proot sakila < sql/sakila-schema.sql

    - name: Load data
      run: mysql -h 127.0.0.1 -uroot -proot sakila < sql/sakila-data.sql

    - name: Run test queries
      run: mysql -h 127.0.0.1 -uroot -proot sakila < sql/queries/actor_queries.sql
